# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0003_message_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='name',
            field=models.CharField(default='Anonymous', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(default='Anonymous', max_length=20),
        ),
    ]
