# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0005_topic_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(),
        ),
    ]
